L'exécution de votre programme a déclenché une exception java.lang.RuntimeException : Désolé Dave, je ne peux pas te laisser utiliser setX(x) dans cet exercice. Marche jusqu'à ton objectif.
 Merci de corriger votre code.
   at plm.runtime4.JediEscaper.setX (plm.runtime4.JediEscaper:10)
   at plm.runtime4.JediEscaper.writeMsg (plm.runtime4.JediEscaper:94)
   at plm.runtime4.JediEscaper$$anonfun$Numerotation$1$$anonfun$apply$mcVI$sp$2.apply$mcVI$sp (plm.runtime4.JediEscaper:110)
   at plm.runtime4.JediEscaper$$anonfun$Numerotation$1$$anonfun$apply$mcVI$sp$2.apply (plm.runtime4.JediEscaper:108)
   at plm.runtime4.JediEscaper$$anonfun$Numerotation$1$$anonfun$apply$mcVI$sp$2.apply (plm.runtime4.JediEscaper:108)
   at scala.collection.immutable.Range.foreach (Range.scala:166)
   at plm.runtime4.JediEscaper$$anonfun$Numerotation$1.apply$mcVI$sp (plm.runtime4.JediEscaper:108)
   at plm.runtime4.JediEscaper$$anonfun$Numerotation$1.apply (plm.runtime4.JediEscaper:107)
   at plm.runtime4.JediEscaper$$anonfun$Numerotation$1.apply (plm.runtime4.JediEscaper:107)
   at scala.collection.immutable.Range.foreach (Range.scala:166)
   at plm.runtime4.JediEscaper.Numerotation (plm.runtime4.JediEscaper:107)
   at plm.runtime4.JediEscaper.run (plm.runtime4.JediEscaper:38)
   at plm.core.lang.JVMCompiledLang.runEntity (null:-1)
   at plm.universe.World$1.run (null:-1)
   at java.lang.Thread.run (Thread.java:745)
