L'exécution de votre programme a déclenché une exception java.lang.RuntimeException : Désolé Dave, je ne peux pas te laisser utiliser setPos(x,y) dans cet exercice. Marche jusqu'à ton objectif.
 Merci de corriger votre code.
   at plm.runtime5.JediEscaper.setPos (plm.runtime5.JediEscaper:18)
   at plm.runtime5.JediEscaper.writeMsg (plm.runtime5.JediEscaper:94)
   at plm.runtime5.JediEscaper$$anonfun$Numerotation$1$$anonfun$apply$mcVI$sp$2.apply$mcVI$sp (plm.runtime5.JediEscaper:109)
   at plm.runtime5.JediEscaper$$anonfun$Numerotation$1$$anonfun$apply$mcVI$sp$2.apply (plm.runtime5.JediEscaper:107)
   at plm.runtime5.JediEscaper$$anonfun$Numerotation$1$$anonfun$apply$mcVI$sp$2.apply (plm.runtime5.JediEscaper:107)
   at scala.collection.immutable.Range.foreach (Range.scala:166)
   at plm.runtime5.JediEscaper$$anonfun$Numerotation$1.apply$mcVI$sp (plm.runtime5.JediEscaper:107)
   at plm.runtime5.JediEscaper$$anonfun$Numerotation$1.apply (plm.runtime5.JediEscaper:106)
   at plm.runtime5.JediEscaper$$anonfun$Numerotation$1.apply (plm.runtime5.JediEscaper:106)
   at scala.collection.immutable.Range.foreach (Range.scala:166)
   at plm.runtime5.JediEscaper.Numerotation (plm.runtime5.JediEscaper:106)
   at plm.runtime5.JediEscaper.run (plm.runtime5.JediEscaper:38)
   at plm.core.lang.JVMCompiledLang.runEntity (null:-1)
   at plm.universe.World$1.run (null:-1)
   at java.lang.Thread.run (Thread.java:745)
