Le monde 'caughtSpeeding' diffère:
caughtSpeeding(60,false) returned Ce test a levé une exception scala.MatchError : (60,false) (of class scala.Tuple2$mcIZ$sp) while 0 were expected.
caughtSpeeding(65,true) returned Ce test a levé une exception scala.MatchError : (65,true) (of class scala.Tuple2$mcIZ$sp) while 0 were expected.

