L'évaluation du script a levé une exception qui n'est pas une ScriptException mais une class java.lang.RuntimeException.
Merci de faire un rapport de bug contre la PLM, avec tous les détails nécessaires pour reproduire le problème.
Message de l'exception: Pas d'engin de script pour Python. Veuillez vérifier votre classpath et autres réglages similaires.
plm.core.lang.ScriptingLanguage.runEntity(Unknown Source)
plm.universe.World$1.run(Unknown Source)
java.lang.Thread.run(Unknown Source)
